apiVersion: v1
kind: Pod
metadata:
  name: pod-volume
spec:
  containers:
  - name: nginx-container
    image: nginx:latest
    volumeMounts:
    - mountPath: "/tmp/data/"
      name: primeiro-volume
  volumes:
  - name: primeiro-volume
    hostPath:
      path: "/tmp/data/"
      type: DirectoryOrCreate